### ISSUE TITLE
Jest unit tests with flow syntax ?

### ISSUE THREAD

**Issue by aksonov** [facebook/flow#1079]
I'm trying to use flow syntax within unit tests, but i don't see any way to test it
```
 - Error: Line 5: Unexpected token :
        at createError (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:2392:21)
        at unexpectedTokenError (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:2467:13)
        at throwUnexpectedToken (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:2472:15)
        at parseClassBody (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:5045:21)
        at parseClassDeclaration (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:5067:21)
        at parseStatementListItem (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:3935:24)
        at parseFunctionSourceElements (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:4766:23)
        at parseFunctionExpression (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:4972:16)
        at parsePrimaryExpression (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:3232:24)
        at inheritCoverGrammar (node_modules/jest-cli/node_modules/istanbul/node_modules/esprima/esprima.js:2648:18)
```

**Comment by jeffmo** [comment]
You probably need to set up a preprocessor (like [babel](https://github.com/babel/babel) with [babel-jest](https://github.com/babel/babel-jest)) in order to strip away Flow syntax before Jest tries to run your tests and code.

**Comment by jeffmo** [comment]
Closing this out for now, but let me know if you have further issues/questions on the matter

**Comment by aksonov** [comment]
I did that, but got that error...

Pavel.

**Comment by aksonov** [comment]
Oh, I see, you meant i need to do convertation to normal javascript as background process, right?
That transpiler doesn’t remove ‘export’ directive for modules and files still cannot be compilable.

Also that way is not fully automatic (requires to run babel watcher, etc.), i believe should be easier way integrated into Node itself…

**Comment by aksonov** [comment]
missed testPathDirs was a key. I thought it will find __tests_ automatically as React docs suggest, but I had to defined it directly.

> 11 нояб. 2015 г., в 4:06 PM, Pavlo Aksonov <aksonov@gmail.com> написал(а):
> 
> Oh, I see, you meant i need to do convertation to normal javascript as background process, right?
> That transpiler doesn’t remove ‘export’ directive for modules and files still cannot be compilable.
> 
> Also that way is not fully automatic (requires to run babel watcher, etc.), i believe should be easier way integrated into Node itself…
>

**Comment by yiakwy** [comment]
suffer from the problem typed sytax not recognized by jest
