### ISSUE TITLE
Build error using null literal type in a union type within a generator function

### ISSUE THREAD

**Issue by JKoff** [facebook/flow#1615]
Hi, I'm not sure if this is the right place to report this, though I'm having trouble using the null literal type to annotate a variable within a generator function with Flow 0.22.1. The following code works:

```javascript
type Test = number | null;

function* testGenerator<T>(): Iterator<T> {
	const test1: Test = 0;
}
```

and so does the following:

```javascript
const test2: (number | null) = 0;
```

But if I try to do:

```javascript
function* testGenerator<T>(): Iterator<T> {
	const test3: (number | null) = 0;
}
```

Then I get the following error:
```
Module build failed: Error: /var/www/pxy-v2/app/lib/generator-utils.jsx: did not recognize object of type "NullLiteralTypeAnnotation"
    at Object.getFieldNames (/var/www/pxy-v2/node_modules/ast-types/lib/types.js:659:15)
    at visitChildren (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:221:32)
    at Visitor.PVp.visitWithoutReset (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:202:16)
    at NodePath.each (/var/www/pxy-v2/node_modules/ast-types/lib/path.js:99:22)
    at visitChildren (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:217:14)
    at Visitor.PVp.visitWithoutReset (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:202:16)
    at visitChildren (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:244:21)
    at Visitor.PVp.visitWithoutReset (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:202:16)
    at visitChildren (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:244:21)
    at Visitor.PVp.visitWithoutReset (/var/www/pxy-v2/node_modules/ast-types/lib/path-visitor.js:202:16)
```

Has anyone run into this? I'm still on Babel 5.8, if that might be a factor.

**Comment by samwgoldman** [comment]
This doesn't look like a Flow issue to me. The stack trace points to ast-types. Have you tried asking over there?

**Comment by JKoff** [comment]
I haven't—I'll try to dig into this a little more and open an issue with ast-types when I have a better understanding of what's going on. Thanks!
