### ISSUE TITLE
New install missing folder flow-bin\vendor\flow?

### ISSUE THREAD

**Issue by EEsterling** [facebook/flow#1616]
Having the most basic of issues.  Just installed flow, and doesn't appear to have installed correctly...  No vendor folder?  I searched this forum and am surprised someone else didn't encounter. 

All I have done is follow the basic instructions from [Getting Started](http://flowtype.org/docs/getting-started.html)

In a new project directory with empty .flowconfig and package.json :
`npm install --save-dev flow-bin
`
**Package.json** has the recommended flow script. 

Try **npm run flow** and get the following.

The error suggests there is no folder at: node_modules\flow-bin\vendor\flow
Sure enough, there is no vendor directory.  

Similar error messages on other packages suggest making sure packages are up to date.  This is a brand new nodejs install and an up to date npm install (v3.8.6) and a brand new flow-bin install. **npm outdated** reports nothing. 

Not sure what the next step is.

```
> flow; test $? -eq 0 -o $? -eq 2

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Source\Test\flow\node_modules\flow-bin\vendor\flow ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by EEsterling** [comment]
Ah.  Scrolling off the top of my page, the npm install reported this:

```
**  x No binary found matching your system. It's probably not supported.
  x flow binary test failed**
```
Looking into that, I see that Windows is not supported:
[https://github.com/facebook/flow/issues/6](https://github.com/facebook/flow/issues/6)
