### ISSUE TITLE
[website] jekyll_flowdoc.rb should convert non-ascii content

### ISSUE THREAD

**Issue by zhenyong** [facebook/flow#2082]
I try to translate *.doc.js to Chinese, then meet errors when build:

```
  Conversion error: Jekyll::FlowdocConverter
 encountered an error while converting '/docs/getting-started.doc.js':
                    undefined method `gsub' for nil:NilClass
...util.rb:37:in `escapeHTML': undefined method `gsub' for nil:NilClass (NoMethodError)
    jekyll_flowdoc.rb:326:in `escape'
    jekyll_flowdoc.rb:460:in `convert'
    /jekyll/renderer.rb:88:in `block in convert'
    /jekyll/renderer.rb:86:in `each'
    /jekyll/renderer.rb:86:in `reduce'
```

The reason may be:

content = "中"
`convert(content)` think length of  content is 1, while `flow ast` think it is 3
## Stupid way to solve

``` ruby
#line 371
    def convert(content)
      # add this line
      content = (content.bytes.map! {|x| x.chr }).join
```

I have never use Ruby, just try to make convertor think length of "中" as 3

**Comment by SamChou19815** [comment]
We no longer use Ruby for the website
