### ISSUE TITLE
Investigate why Flow doesn't work on 32 bit Ubuntu

### ISSUE THREAD

**Issue by gabelevi** [facebook/flow#270]
We should look into what exactly doesn't work on 32 bit machines and if it is easy to fix.

[Reported on reddit](https://www.reddit.com/r/javascript/comments/2wn3rf/flow_the_js_typechecker_by_facebook_no_longer/cosdy92).

**Comment by jwatzman** [comment]
My suspicion is that there's some subtle pointer size bug in hh_shared.c where we assume pointers are 8 bytes or something like that. Skimming the code, the hash stuff looks suspicious -- it uses "unsigned long" whose size I think goes from 8 to 4 bytes when you go 64 to 32 bit; that probably should be uint64_t. Possibly a similar error in ocaml land, assuming things about size. This stuff is all fixable.

May also be in the ocaml *runtime* where we integer overflow their integers, due to needing bigger int sizes for hash table stuff or something like that. This will be much harder to deal with.

**Comment by jwatzman** [comment]
Also @pikatchu just explained why -- the dep table is a combo of 2 32-bit hashes, into one 64-bit value so you can CAS it atomically.

**Comment by TrySound** [comment]
Is this still relevant?

**Comment by Xunnamius** [comment]
I use an Odroid (so ARM) Ubuntu 16.04 and it's relevant for me. Fortunately, I can run Flow through ESLint on Sublime on Windows and sidestep having to use the CLI tool at all, but this is still unfortunate.

**Comment by kiler129** [comment]
Also this fails with very weird message which is hard to debug, which I'm going to leave here for anyone googling and wtf-ing:

```
Starting: /usr/bin/yarn run eslint --no-color /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/assets/
in directory: /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff
yarn run v1.7.0
$ /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/.bin/eslint --no-color /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/assets/	
    "file" argument must be a non-empty string
    TypeError: "file" argument must be a non-empty string
        at normalizeSpawnArguments (child_process.js:383:11)
        at Object.spawnSync (child_process.js:519:38)
        at spawnFlow (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/collect.js:150:39)
        at collect (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/collect.js:174:16)
        at Program (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/index.js:83:46)
        at listeners.(anonymous function).forEach.listener (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/safe-emitter.js:45:58)
        at Array.forEach (<anonymous>)
        at Object.emit (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/safe-emitter.js:45:38)
        at NodeEventGenerator.applySelector (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/node-event-generator.js:251:26)
        at NodeEventGenerator.applySelectors (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    error Command failed with exit code 2.
    Process exited with code 1
```

**Comment by kiler129** [comment]
Also this fails with weird errors when ran from `eslint`, which is impossible to debug and returns no results while googling.

I'm going to leave this message here for any people looking for it:
```
Starting: /usr/bin/yarn run eslint --no-color /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/assets/
in directory: /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff
yarn run v1.7.0
$ /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/.bin/eslint --no-color /opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/assets/
    "file" argument must be a non-empty string
    TypeError: "file" argument must be a non-empty string
        at normalizeSpawnArguments (child_process.js:383:11)
        at Object.spawnSync (child_process.js:519:38)
        at spawnFlow (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/collect.js:150:39)
        at collect (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/collect.js:174:16)
        at Program (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint-plugin-flowtype-errors/dist/index.js:83:46)
        at listeners.(anonymous function).forEach.listener (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/safe-emitter.js:45:58)
        at Array.forEach (<anonymous>)
        at Object.emit (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/safe-emitter.js:45:38)
        at NodeEventGenerator.applySelector (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/node-event-generator.js:251:26)
        at NodeEventGenerator.applySelectors (/opt/jetbrains/TeamCity/buildAgent/work/f613c80626aaf1ff/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    error Command failed with exit code 2.
    Process exited with code 1
```
