### ISSUE TITLE
https://flowtype.org/try/ fails with JS error using 0.37.0 flow version

### ISSUE THREAD

**Issue by pbomb** [facebook/flow#3011]
[https://flowtype.org/try/](https://flowtype.org/try/) no longer works unless you explicitly downgrade from the default flow version with the following JS error:
```
flow.js:587 Uncaught (in promise) Error: re_string_match: not implemented in JS
    at aNm (https://flowtype.org/assets/v0.37.0/flow.js:587:13)
    at rH (https://flowtype.org/assets/v0.37.0/flow.js:2895:3)
    at rK (https://flowtype.org/assets/v0.37.0/flow.js:2901:7)
    at r9 (https://flowtype.org/assets/v0.37.0/flow.js:3086:23)
    at l_ (https://flowtype.org/assets/v0.37.0/flow.js:3087:3)
    at mc (https://flowtype.org/assets/v0.37.0/flow.js:3109:15)
    at sj (https://flowtype.org/assets/v0.37.0/flow.js:3450:15)
    at sp (https://flowtype.org/assets/v0.37.0/flow.js:3480:10)
    at https://flowtype.org/assets/v0.37.0/flow.js:17683:37
    at b (https://flowtype.org/assets/v0.37.0/flow.js:591:27)
    at p (https://flowtype.org/assets/v0.37.0/flow.js:736:10)
aNm @ flow.js:587
rH @ flow.js:2895
rK @ flow.js:2901
r9 @ flow.js:3086l_ @ flow.js:3087
mc @ flow.js:3109
sj @ flow.js:3450
sp @ flow.js:3480
(anonymous function) @ flow.js:17683
b @ flow.js:591p @ flow.js:736
sr @ flow.js:3497
(anonymous function) @ flow.js:17668
b @ flow.js:591
p @ flow.js:736
w3 @ flow.js:17668
aLR @ flow.js:17697
ck @ flow.js:66
(anonymous function) @ flow.js:363
(anonymous function) @ tryFlow.js:11294
Promise.resolve (async)
getAnnotations @ tryFlow.js:11293
lintAsync @ tryFlow.js:9226
startLinting @ tryFlow.js:9240
(anonymous function) @ tryFlow.js:9331
CodeMirror @ tryFlow.js:7258
CodeMirror @ tryFlow.js:7204
(anonymous function) @ tryFlow.js:11435
execCb @ prelude.js:1694
check @ prelude.js:882
enable @ prelude.js:1174
init @ prelude.js:787
(anonymous function) @ prelude.js:1458
setTimeout (async)
(anonymous function) @ prelude.js:1813
localRequire @ prelude.js:1447
requirejs @ prelude.js:1795
createEditor @ tryFlow.js:11363
(anonymous function) @ (index):90
execCb @ prelude.js:1694
check @ prelude.js:882
(anonymous function) @ prelude.js:1137
(anonymous function) @ prelude.js:135
(anonymous function) @ prelude.js:1187
each @ prelude.js:60
emit @ prelude.js:1186
check @ prelude.js:937
enable @ prelude.js:1174
init @ prelude.js:787
callGetModule @ prelude.js:1201
completeLoad @ prelude.js:1588
onScriptLoad @ prelude.js:1715
```

**Comment by pbomb** [comment]
ugh, saw that this is a duplicate
