### ISSUE TITLE
Error ENOENT in NixOS

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#4093]
Running flow (inside a nix-shell of NixOS, with babel.. etc all working) results in:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /nix/store/awnbs7rn2q75cjjpygxhswpf6i1f7g2j-node-dependencies-polykey-0.0.1/lib/node_modules/flow-bin/flow-linux64-v0.47.0/flow ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It appears flow is trying to spawn a child process, but perhaps something is lacking in the nix-shell environment that prevents this from happening, what could that requirement be? A specific executable, path, resource or something else?

**Comment by rimmington** [comment]
See https://github.com/flowtype/flow-bin/issues/62
