### ISSUE TITLE
Flow doesn't work anymore

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5799]
Really not sure what is happening.  I can not get Flow to work at all anymore.  I just get tons of errors.  Its like the whole thing is broken.

Nuclide is providing the following:

```
Uncaught (in promise) RpcTimeoutError: Timeout after 60000 for id: 44, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2018-02-09T21:58:40.016Z] [ERROR] datatip - Error getting datatip from provider nuclide-type-hint

 Timeout after 60000 for id: 46, Calling remote method typeHint..
RpcTimeoutError: Timeout after 60000 for id: 46, Calling remote method typeHint..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
````

**Comment by bradennapier** [comment]
Fixed itself?  Not sure what happened
