### ISSUE TITLE
suppress_comment example in Advanced Configuration crashes flow

### ISSUE THREAD

**Issue by JavascriptMick** [facebook/flow#665]
Problem with documentation only.  This is the suggested syntax..

suppress_comment: \(.\|\n\)*\$FlowFixMe

When I put this in my .flowconfig, I get the below error.  Should be this instead I think

suppress_comment=.*\$FlowFixMe

Error:-
undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/michael/Tutorials/node/clickforce_es6/node_modules/gulp-flowtype/lib/index.js:87:33
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by TrySound** [comment]
Fixed https://flow.org/en/docs/config/options/#toc-suppress-comment-regex
