### ISSUE TITLE
Unable to install `flow-upgrade`

### ISSUE THREAD

**Issue by pascalduez** [facebook/flow#7528]
`flow-upgrade@1.1.0`

`node -v: 10.12.0`
`npm -v: 6.7.0`

## Actual behavior

`npm i -g flow-upgrade`

```
➜ npm i -g flow-upgrade@latest

> ast-types@0.12.0 prepack /[...]/.npm/_cacache/tmp/git-clone-d8fd76e8
> npm run clean && npm run gen && npm run build

> ast-types@0.12.0 clean /[...]/.npm/_cacache/tmp/git-clone-d8fd76e8
> ts-emit-clean

sh: 1: ts-emit-clean: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ast-types@0.12.0 clean: `ts-emit-clean`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ast-types@0.12.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /[...]/.npm/_logs/2019-03-05T09_38_10_355Z-debug.log
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /[...]/.npm/_logs/2019-03-05T09_38_10_389Z-debug.log
```

```
574 569 silly resolveWithNewModule esprima@4.0.1 checking installable status
575 570 info lifecycle ast-types@0.12.0~prepack: ast-types@0.12.0
576 571 verbose lifecycle ast-types@0.12.0~prepack: unsafe-perm in lifecycle true
578 573 verbose lifecycle ast-types@0.12.0~prepack: CWD: /[...]/.npm/_cacache/tmp/git-clone-d8fd76e8
579 574 silly lifecycle ast-types@0.12.0~prepack: Args: [ '-c', 'npm run clean && npm run gen && npm run build' ]
580 575 silly lifecycle ast-types@0.12.0~prepack: Returned: code: 1  signal: null
581 576 info lifecycle ast-types@0.12.0~prepack: Failed to exec prepack script
582 577 silly fetchPackageMetaData error for ast-types@git://github.com/jbrown215/ast-types.git premature close
583 578 timing stage:rollbackFailedOptional Completed in 5ms
584 579 timing stage:runTopLevelLifecycles Completed in 15424ms
585 580 verbose stack Error: premature close
586 580 verbose stack     at PassThrough.onclose (/[...]/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
587 580 verbose stack     at PassThrough.emit (events.js:187:15)
588 580 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)
589 580 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
590 581 verbose cwd /[...]/
591 582 verbose Linux 4.15.0-45-generic
592 583 verbose argv "/[...]/.nvm/versions/node/v10.12.0/bin/node" "/[...]/.nvm/versions/node/v10.12.0/bin/npm" "i" "-g" "flow-upgrade@latest"
593 584 verbose node v10.12.0
594 585 verbose npm  v6.7.0
595 586 error premature close
596 587 verbose exit [ 1, true ]
~                                                                                                                                                             
~           
```

**Comment by HarisSpahija** [comment]
Possibly related issue to [tsc crashing on scripts](https://github.com/Microsoft/TypeScript/issues/8186)?

**Comment by HarisSpahija** [comment]
I was able to reproduce the issue by following your steps. Here is my log:


```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/harisspahija/.nvm/versions/node/v11.13.0/bin/node',
1 verbose cli   '/Users/harisspahija/.nvm/versions/node/v11.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'clean' ]
2 info using npm@6.9.0
3 info using node@v11.13.0
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle ast-types@0.12.0~preclean: ast-types@0.12.0
6 info lifecycle ast-types@0.12.0~clean: ast-types@0.12.0
7 verbose lifecycle ast-types@0.12.0~clean: unsafe-perm in lifecycle true
8 verbose lifecycle ast-types@0.12.0~clean: PATH: /Users/harisspahija/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/harisspahija/.npm/_cacache/tmp/git-clone-2982abfa/node_modules/.bin:/Users/harisspahija/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/harisspahija/.npm/_cacache/tmp/git-clone-2982abfa/node_modules/.bin:/Users/harisspahija/.nvm/versions/node/v11.13.0/bin:/Users/harisspahija/Library/Android/sdk/emulator:/Users/harisspahija/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/harisspahija/.nvm/versions/node/v11.13.0/bin:/Users/harisspahija/Library/Android/sdk/:/Users/harisspahija/Library/Android/sdk//tools:/Users/harisspahija/Library/Android/sdk//platform-tools
9 verbose lifecycle ast-types@0.12.0~clean: CWD: /Users/harisspahija/.npm/_cacache/tmp/git-clone-2982abfa
10 silly lifecycle ast-types@0.12.0~clean: Args: [ '-c', 'ts-emit-clean' ]
11 info lifecycle ast-types@0.12.0~clean: Failed to exec clean script
12 verbose stack Error: ast-types@0.12.0 clean: `ts-emit-clean`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/Users/harisspahija/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:193:13)
12 verbose stack     at maybeClose (internal/child_process.js:1001:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
13 verbose pkgid ast-types@0.12.0
14 verbose cwd /Users/harisspahija/.npm/_cacache/tmp/git-clone-2982abfa
15 verbose Darwin 18.2.0
16 verbose argv "/Users/harisspahija/.nvm/versions/node/v11.13.0/bin/node" "/Users/harisspahija/.nvm/versions/node/v11.13.0/bin/npm" "run" "clean"
17 verbose node v11.13.0
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error ast-types@0.12.0 clean: `ts-emit-clean`
23 error spawn ENOENT
24 error Failed at the ast-types@0.12.0 clean script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jbrown215** [comment]
This should be fixed now. Please re-open if you continue to have problems with `flow-upgrade`. Thank you for reporting!
