### ISSUE TITLE
flow-osx folder missing after installing flow in fresh react-native 0.61.5 project on macOS

### ISSUE THREAD

**Issue by phutflesz** [facebook/flow#8225]
In addition to the commands below I'm also trying to use the flow-for-vscode extension for VS Code, which says the following (as long as I don't delete the .flowconfig of course):
[myproject/.flowconfig] Failed to start flow Error: Couldn't find the '/Users/me/Documents/myproject/node_modules/flow-bin/flow-osx-v0.105.0/flow' binary. Make sure it's installed and in your $PATH. I don't want to add anything project-specific to my global $PATH, and I specified the settings as instructed in the installation guide:
"flow.pathToFlow": "${workspaceFolder}/node_modules/.bin/flow"
Nevertheless, it keeps complaining about this flow-osx-v0.105.0 folder. It indeed doesn't exist, but I can't find any docs saying I should install anything that I didn't already install:
```
"devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "@babel/preset-flow": "^7.7.4",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "flow-bin": "^0.105.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
}
```

Flow version: 0.105.0 (as required in pre-existing .flowconfig)

## Expected behavior
After
npm install --save-dev @babel/core @babel/cli @babel/preset-flow
and
npm install --save-dev flow-bin@0.105.0
and adding "flow" to the scripts section in package.json, I would expect that
npm run flow init
would work after temporarily deleting the pre-existing .flowconfig.

## Actual behavior
```
macbook:myproject me$ npm run flow init

> myproject@0.0.1 flow /Users/me/Documents/myproject
> flow "init"

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/me/Documents/myproject/node_modules/flow-bin/flow-osx-v0.105.0/flow ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@0.0.1 flow: `flow "init"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myproject@0.0.1 flow script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2019-12-12T10_16_08_769Z-debug.log
```

The mentioned log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'flow',
1 verbose cli   'init' ]
2 info using npm@6.9.0
3 info using node@v10.16.2
4 verbose run-script [ 'preflow', 'flow', 'postflow' ]
5 info lifecycle myproject@0.0.1~preflow: myproject@0.0.1
6 info lifecycle myproject@0.0.1~flow: myproject@0.0.1
7 verbose lifecycle myproject@0.0.1~flow: unsafe-perm in lifecycle true
8 verbose lifecycle myproject@0.0.1~flow: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/me/Documents/myproject/node_modules/.bin:/Users/me/bin:/Users/me/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle myproject@0.0.1~flow: CWD: /Users/me/Documents/myproject
10 silly lifecycle myproject@0.0.1~flow: Args: [ '-c', 'flow "init"' ]
11 silly lifecycle myproject@0.0.1~flow: Returned: code: 1  signal: null
12 info lifecycle myproject@0.0.1~flow: Failed to exec flow script
13 verbose stack Error: myproject@0.0.1 flow: `flow "init"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid myproject@0.0.1
15 verbose cwd /Users/me/Documents/myproject
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "flow" "init"
18 verbose node v10.16.2
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error myproject@0.0.1 flow: `flow "init"`
22 error Exit status 1
23 error Failed at the myproject@0.0.1 flow script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by phutflesz** [comment]
Alright, I found it. I had a problem in the same category yesterday when I started setting up the react-native project, shortly before this problem popped up... Wrong version.
Source: https://github.com/flowtype/flow-bin/issues/166
Required binaries for the 0.150.0 release were not properly uploaded. I changed the version of Flow to 0.150.2 and it seems to work now.
Sorry if this ticket is in the wrong spot here.

For reference if someone else stumbles across this, the previous problem I had was an "Unable to load script" redbox when I ran `npx react-native run-android`, or an "Invalid regular expression" error in blacklist.js when I tried `npx react-native start`.
The solution to this problem was the wrong version of nodejs which was installed using the default command from the Getting Started guide. Instead I have to force npm to install nodejs v10.16.3 (source https://github.com/facebook/react-native/issues/26598#issuecomment-537767015), then it works.
