### ISSUE TITLE
flow-dev-tools add-comment throws uncaught rejection

### ISSUE THREAD

**Issue by ianduvall** [facebook/flow#8459]
flow-dev-tools's `add-comment` command throws the following uncaught error:
```
uncaught rejection
TypeError: newValue.error_codes is not iterable
```

Flow version: 1.22.0

## Expected behavior

Running `add-comments` completes successfully

## Actual behavior

Terminal output on OSX:
```
../flow/tool add-comments --all --bin /path/to/flow --check check --comment "\$FlowIssue - upgrade v0.122.0" .
uncaught rejection
TypeError: newValue.error_codes is not iterable
TypeError: newValue.error_codes is not iterable
    at joinSuppression (/.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:645:37)
    at /.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:649:21
    at Generator.next (<anonymous>)
    at step (/.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:753:191)
    at /.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:753:437
    at new Promise (<anonymous>)
    at /.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:753:99
    at addComments (/.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:603:18)
    at /.../flow/packages/flow-dev-tools/src/comment/add-commentsRunner.js:164:9
    at Generator.next (<anonymous>)
```

**Comment by ianduvall** [comment]
It seems this issue is with the main branch. Checking out the v0.122 branch seems to resolve this issue.
